Repository agiresearch/OpenAGI, pull requests merged in 2024-05, with the labels that each got.

#42 feat: add output of agent waiting time and agent turnaround time
  openagi/src/agents/agent_process.py
  openagi/src/agents/base.py
  openagi/src/agents/native_agents/math_agent/math_agent.py
  openagi/src/agents/native_agents/narrative_agent/narrative_agent.py
  openagi/src/agents/native_agents/rec_agent/rec_agent.py
Labels: add feature

#43 fix: change the name of agent execution time to agent turnaround time
  openagi/src/agents/base.py
  openagi/src/agents/native_agents/math_agent/math_agent.py
  openagi/src/agents/native_agents/narrative_agent/narrative_agent.py
  openagi/src/agents/native_agents/rec_agent/rec_agent.py
Labels: fix bug

#47 feat: convert multi-thread with multi-process
  openagi/src/agents/agent_factory.py
  openagi/src/agents/agent_process.py
  openagi/src/agents/base.py
  openagi/src/agents/native_agents/math_agent/math_agent.py
Labels: add feature, refactor

#50 feat: add tool calling for chatgpt-based math agent
  openagi/src/agents/agent_config/MathAgent.json
  openagi/src/agents/agent_factory.py
  openagi/src/agents/agent_process.py
  openagi/src/agents/base.py
  openagi/src/agents/native_agents/math_agent/math_agent.py
  openagi/src/agents/native_agents/narrative_agent/narrative_agent.py
  openagi/src/agents/native_agents/rec_agent/rec_agent.py
  openagi/src/tools/online/currency_converter.py
  openagi/src/utils/message.py
Labels: add feature, refactor

#51 style: add log when math agent starts calling external tools
  openagi/src/agents/native_agents/math_agent/math_agent.py
Labels: change style

#52 docs: add instructions of how to set up external tools
  README.md
  tools.md
Labels: add documentation

#53 docs: fix .env.example
  .env.example
Labels: add documentation

#62 feat: Add a LlamaIndex-based RAG agent
  .gitignore
  openagi/src/agents/agent_config/RAGAgent.json
  openagi/src/agents/agent_factory.py
  openagi/src/agents/native_agents/rag_agent/data/paul_graham/paul_graham_essay.txt
  openagi/src/agents/native_agents/rag_agent/rag_agent.py
  requirements.txt
Labels: add feature
